04. WEB/05. MVC Practice/DrinkAndGo/DrinkAndGo.Web/Controllers/ContactsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DrinkAndGo.Web.Controllers
{
    public class ContactsController : Controller
    {
        public ViewResult Index()
        {
            return View();
        }
    }
}

04. WEB/05. MVC Practice/DrinkAndGo/DrinkAndGo.Web/Controllers/ShoppingCartsController.cs
using DrinkAndGo.Web.Models;
using DrinkAndGo.Web.Models.Contracts;
using DrinkAndGo.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace DrinkAndGo.Web.Controllers
{
    public class ShoppingCartsController : Controller
    {
        private readonly IDrinkRepository drinkRepository;
        private readonly ShoppingCart shoppingCart;

        public ShoppingCartsController(IDrinkRepository drinkRepository, ShoppingCart shoppingCart)
        {
            this.drinkRepository = drinkRepository;
            this.shoppingCart = shoppingCart;
        }
        public ViewResult Index()
        {
            var items = this.shoppingCart.GetShoppingCartItems();
            this.shoppingCart.ShoppingCartItems = items;

            var shopingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart = this.shoppingCart,
                ShoppingCartTotal = this.shoppingCart.GetShoppingCartTotal()
            };

            return View(shopingCartViewModel);
        }

        public RedirectToActionResult AddToShoppingCart(int drinkId)
        {
            var selectedDrink = this.drinkRepository.Drinks.FirstOrDefault(d => d.Id == drinkId);

            if (selectedDrink != null)
            {
                this.shoppingCart.AddToCart(selectedDrink, 1);
            }

            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int drinkId)
        {
            var selectedDrink = this.drinkRepository.Drinks.FirstOrDefault(d => d.Id == drinkId);

            if (selectedDrink != null)
            {
                this.shoppingCart.RemoveFromCart(selectedDrink);
            }

            return RedirectToAction("Index");
        }
    }
}

04. WEB/05. MVC Practice/DrinkAndGo/DrinkAndGo.Web/Views/Shared/Carousel.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner" role="listbox">
        <div class="carousel-item active">
            <img class="d-block w-100" src="/Images/carousel01.jpg" data-src="holder.js/900x400?theme=social" alt="First slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="/Images/carousel02.jpg" data-src="holder.js/900x400?theme=industrial" alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="/Images/carousel03.jpg"data-src="holder.js/900x400?theme=industrial" alt="Second slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

04. WEB/05. MVC Practice/DrinkAndGo/DrinkAndGo.Web/Views/Shared/DrinkPartial.cshtml
@model Drink

   <div class="col-sm-4 col-lg-4 col-md-4 align">
            <div class="img-thumbnail">
                <img src="@Model.ImageThumbnailUrl" alt="" class="img-fluid" />
                <div class="figure-caption">
                    <h4 class="float-right">@Model.Price.ToString("c")</h4>
                    <h4 class="text-info">
                        <a>@Model.Name</a>
                    </h4>
                    <p>@Model.ShortDescription</p>
                </div>
                <div class=" addToCart text-right">
                    <p class="btn">
                        <a class="btn-success" id="cartButton"
                           asp-controller="ShoppingCarts"
                           asp-action="AddToShoppingCart"
                           asp-route-drinkId="@Model.Id">
                            @**Or asp-route-Id*@
                            Add to cart
                        </a>
                    </p>
                </div>
            </div>
        </div>

04. WEB/05. MVC Practice/DrinkAndGo/DrinkAndGo.Web/Views/Shared/LoginPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Identity.EntityFrameworkCore

@inject SignInManager<IdentityUser> SignInManager

@if (SignInManager.IsSignedIn(User))
{
    <form asp-area="" asp-controller="Account" asp-action="Logout" id="logoutForm"
          method="post" class="navbar-right">
        <ul class="nav navbar-nav navbar-right">
            <li><a class="nav-link text-light" href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
        </ul>
    </form>
}
else
{
    <ul class="nav navbar-nav ml-auto">
        <li class="nav-item active"><a class="nav-link text-light" id="registerLink" asp-controller="Account" asp-action="Register"> Register </a></li>
        <li class="nav-item"><a class="nav-link text-light" id="loginLink" asp-controller="Account" asp-action="Login"> Log in </a></li>
    </ul>
}

04. WEB/05. MVC Practice/DrinkAndGo/DrinkAndGo.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DrinkAndGo.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome-4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark fixed-top bg-dark">
        <div class="container container-fluid">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm" id="navbarSupportedContent">

                <ul class="nav navbar-nav">
                    @*nav navbar-nav mr-auto*@
                    <li class="nav-item"><a class="nav-link text-light" asp-controller="Home" asp-action="Index"> Home </a></li>
                    @await Component.InvokeAsync("CategoryMenu")
                    <li class="nav-item"><a class="nav-link text-light" asp-controller="Contacts" asp-action="Index">Contact Us</a></li>

                    @await Component.InvokeAsync("ShoppingCartSummary")
                </ul>
                <ul class="navbar-nav ml-auto">
                    @await Html.PartialAsync("LoginPartial")
                </ul>

            </div>
        </div>
    </nav>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - DrinkAndGo.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>